language: node_js
node_js:
    - stable
branches:
    only:
        - master
before_script:
    - npm install -g @angular/cli
script:
    - ng lint
    - ng build --prod --basehref https://ridikon.github.io/todos-app/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist

