language: node_js
node_js:
    - stable
script:
    - ng build --prod --base-href https://ridikon.github.io/todos-app/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/my-todos-app
